// session_timeout_view.slint
import { Button, VerticalBox } from "std-widgets.slint";

export component SessionTimeoutView inherits VerticalBox {
    callback re-unlock(string);
    in-out property <string> password: "";

    alignment: center;
    spacing: 20px;

    Text {
        text: "SESSION TIMEOUT: VAULT LOCKED";
        font-size: 18px;
        font-weight: 700;
        color: #FF3B30; // Red color for alerts
    }

    TextInput {
        width: 280px;
        height: 40px;
        text <=> password;
        vertical-alignment: center;
    }

    Button {
        width: 280px;
        height: 40px;
        text: "Re-Unlock";
        primary: true;
        clicked => { re-unlock(password) }
    }
}