// unlock_view.slint
import { Button, VerticalBox } from "std-widgets.slint";

export component UnlockView inherits VerticalBox {
    callback unlock-vault(string);
    callback first-time-setup();

    in-out property <string> master-password: "";

    alignment: center;
    spacing: 20px;

    Text {
        text: "🔐 RVault";
        font-size: 24px;
        font-weight: 700;
        color: #FFFFFF;
    }

    TextInput {
        width: 280px;
        height: 40px;
        text <=> master-password;
        vertical-alignment: center;
        input-type: password;
    }

    Button {
        width: 280px;
        height: 40px;
        text: "Unlock Vault";
        primary: true;
        clicked => { unlock-vault(master-password) }
    }

    Button {
        width: 280px;
        height: 40px;
        text: "First Time Setup";
        clicked => { first-time-setup() }
    }
}